name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ci
      run: |
        git clone -b multiplatform https://github.com/fwilhe2/Inzell
        cd Inzell
        ./gradlew publishToMavenLocal
        cd ..
        cd kotlin-jvm-mvn
        mvn exec:java
