name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Install Inzell Devel version
        run: |
          git clone https://github.com/fwilhe2/Inzell
          cd Inzell
          ./gradlew publishToMavenLocal
      - name: Run jvm kotlin example
        run: |
          cd kotlin-jvm-mvn
          mvn package exec:java
      - name: Run jvm java example
        run: |
          cd java-mvn
          mvn package exec:java
      - name: Run kotlin nodejs example
        run: |
          cd kotlin-js-node
          ./gradlew nodeRun
      # - name: Build browserDistribution
      #   run: |
      #     cd js-browser
      #     ./gradlew browserDistribution
      #     cd ..
      #     mkdir public
      #     cp -r js-browser/build/distributions/* public/
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     target_branch: gh-pages
      #     build_dir: public
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
